/**
 * @file device_config.c
 * @brief PIC16F876A microcontroller fuse configuration
 * @author Sébastien Celles
 * @date 2025
 * @version 1.0
 *
 * @details This file contains exclusively the fuse configuration (configuration bits)
 *          of the PIC16F876A microcontroller. These parameters are fixed during programming
 *          and determine the fundamental behavior of the microcontroller.
 *
 * @par Hardware configuration:
 * - **Oscillator**: HS (High Speed) for external crystal
 * - **Frequency**: Designed to work with a 4MHz crystal
 * - **Debug mode**: Disabled (RB3 available as I/O)
 * - **Protections**: All disabled to facilitate development
 *
 * @par Security and protection:
 * - **Code protection**: OFF (facilitates development)
 * - **EEPROM protection**: OFF
 * - **Write protection**: OFF
 * - **LVP programming**: OFF (RB3 free for I/O)
 *
 * @par Power management:
 * - **Brown-out reset**: OFF (no voltage monitoring)
 * - **Power-up timer**: OFF (fast startup)
 * - **Watchdog timer**: OFF (no software monitoring)
 *
 * @warning These parameters are final when programming the microcontroller.
 *          Any modification requires complete reprogramming.
 *
 * @warning The HS oscillator requires the use of an external crystal.
 *          Verify the presence of the crystal and its capacitors on your board.
 *
 * @note In development mode, all protections are disabled.
 *       For a production version, consider enabling certain protections.
 *
 * @note This file is separated from the main code for better organization
 *       and to avoid pragma config redefinitions.
 *       The file name is inspired by the naming convention used in PIC projects
 *       generated by MCC (MPLAB Code Configurator).
 *
 * @example
 * @code
 * // This file is not included directly in user code.
 * // It is automatically taken into account during compilation.
 * // Parameters are applied when programming the PIC.
 * @endcode
 *
 * @see PIC16F876A datasheet section "Special Features" for fuse details
 * @see device_config.h for system frequency definitions
 */

/**
 * @name Microcontroller configuration
 * @brief PIC16F876A fuse configuration
 * @{
 */

/** @brief Code protection disabled */
#pragma config CP = 1 // Flash Program Memory Code Protection bit (Code protection off)

/** @brief In-circuit debugger disabled */
#pragma config DEBUG = 1 // In-Circuit Debugger Mode bit (In-Circuit Debugger disabled)

/** @brief Write protection disabled */
#pragma config WRT = 3 // Flash Program Memory Write Enable bits (Write protection off; all program memory may be written to by EECON control)

/** @brief EEPROM data protection disabled */
#pragma config CPD = 1 // Data EEPROM Memory Code Protection bit (Data EEPROM code protection off)

/** @brief Low voltage programming disabled */
#pragma config LVP = 0 // Low-Voltage (Single-Supply) In-Circuit Serial Programming Enable bit (RB3 is digital I/O, HV on MCLR must be used for programming)

/** @brief Brown-out reset disabled */
#pragma config BOREN = 0 // Brown-out Reset Enable bit (BOR disabled)

/** @brief Power-up timer disabled */
#pragma config PWRTE = 1 // Power-up Timer Enable bit (PWRT disabled)

/** @brief Watchdog timer disabled */
#pragma config WDTE = 0 // Watchdog Timer Enable bit (WDT disabled)

/** @brief High speed oscillator selected */
#pragma config FOSC = 2 // Oscillator Selection bits (HS oscillator)

/** @} */